#159316712 Hosting on Heroku
andela/rivendell-ah pull request #17
Opened 2018-08-01 22:36 UTC by tutugodfrey

#### What does this PR do?
- Add configurations to host app on heroku

#### Description of Task to be completed?
- create heroku pipeline
- create heroku apps for staging and production
- update default app.json
- add Procfile and script for starting the application

#### How should this be manually tested?
- heroku pipeline will generate a review app on everypull request
- the current state of the application can be tested from the generated review app

#### What are the relevant pivotal tracker stories?
#159316712

2018-08-01 23:51 UTC, megame24 commented on routes/index.js
> +router.get("/api", (req, res) => {
Why did you edit this route?

2018-08-02 06:53 UTC, chidioguejiofor requested changes
Please modify your PR to add the link to the Heroku app and also add some screenshots that show you consuming some of the endpoints from the Heroku app link. 
Once this is done notify me to approve your PR

2018-08-02 06:53 UTC, chidioguejiofor commented on Procfile
> +web: node index.js
Add New Line at the end of file

2018-08-02 09:00 UTC, megame24 commented on routes/index.js
> +router.get("/api", (req, res) => {
Why did you edit this route? This update will cut off entry to all the other routes and controllers, please attend to it.

2018-08-02 09:04 UTC, megame24 reviewed
Please attend to chidi's request.

2018-08-02 09:14 UTC, megame24 commented on routes/index.js
> +router.get("/api", (req, res) => {
Why did you edit this route? By updating this route, you have cut off the rest of the routes and controllers. Please attend to it by reversing the changes.

2018-08-02 09:22 UTC, megame24 approved these changes

2018-08-02 12:51 UTC, closed without merging