#159204702 Users should be able to follow each other
andela/rivendell-ah pull request #35
Opened 2018-08-13 09:27 UTC by mppdg

#### What does this PR do?
- This PR allows users in the system to be able to follow and unfollow each other

#### Description of Task to be completed?
- create `articleFollower` model as a join model for authors and followers relationship
- add associations/relations for the `user` and `articleFollower` models
- create `POST  /profiles/:username/follow` route to enable a login user to follow another user
- create `DELETE  /profiles/:username/follow` route to enable a login user to unfollow a user
- create `GET /profiles/:username/followers` route allows a user to view all his followers
- create `GET /profiles/:username/followings` route allows a user to view all those he is following
- add `AuthorFollowers` class that has static methods to handle the routes above 

#### How should this be manually tested?
- setup the postgres database
- run `npm install` to  dependencies
- run  `sequelize db:migrate` to run migration
- start the server and test the above routes with Postman

#### Any background context you want to provide?

#### What are the relevant pivotal tracker stories?
#159204702

#### Screenshots
- Postman screenshot on successfully the follow endpoint
![image](https://user-images.githubusercontent.com/39072402/44023755-33b5d75a-9ee3-11e8-8142-c5d66afbb31b.png)

- Postman screenshot on successfully the followers endpoint
![image](https://user-images.githubusercontent.com/39072402/44023814-63e48cd2-9ee3-11e8-9405-9c7749ac035d.png)

- Postman screenshot on successfully the followings endpoint
![image](https://user-images.githubusercontent.com/39072402/44023834-7763787c-9ee3-11e8-88b8-05748aa181a3.png)

2018-08-14 16:14 UTC, JCanaks commented on server/controllers/UserFollowerController.js
> +        errors: { message: 'You don\'t need to follow yourself' },
a better message format 'You Cannot follow yourself'

2018-08-14 16:17 UTC, JCanaks commented on server/controllers/UserFollowerController.js
> +                  message: 'You weren\'t following this Author',
Again a better message format would be e.g. 'You are not following this author'

2018-08-15 08:38 UTC, chidioguejiofor commented on server/controllers/FollowController.js
> +              return res.status(422).json({
why do you use 422(Unprocessable Entity) when the server understands the request? I think `404 or 400`  makes  more sense

2018-08-15 08:38 UTC, chidioguejiofor commented on server/controllers/FollowController.js
> +        user.getFollowers()
You can add the followers in an `include` while querying the `User` model. This should be more efficient than running 2 queries

2018-08-15 08:38 UTC, chidioguejiofor commented on server/controllers/FollowController.js
> +        user.getFollowings()
I think it is the same thing here. You can use an `include` in the first query

2018-08-15 08:43 UTC, JCanaks approved these changes

2018-08-15 08:55 UTC, chidioguejiofor reviewed
Nice work! Just a few comments

2018-08-15 08:55 UTC, chidioguejiofor commented on server/controllers/FollowController.js
> +    User.findById(userId)
use attributes to return just the amount of information you need here

2018-08-15 09:03 UTC, tutugodfrey commented on server/database/models/follow.js
> +      as: 'follwed', foreignKey: 'followingId',
I think you this is a misspell `follwed`

2018-08-15 09:03 UTC, tutugodfrey commented on server/test/routes/follow.test.js
> +            chai.request(server)
Good work, but I think you should use 2 space/ 1 tab indentation to maintain consistency with the rest of the codebase

2018-08-15 09:03 UTC, tutugodfrey commented on server/routes/api/follow.js
> +  AuthMiddleware.authenticateUser, AuthMiddleware.verifyUser,
For all instance of this occurrence, why not completely break the middleware to a newline.

2018-08-15 16:35 UTC, chidioguejiofor submitted a review, later dismissed

2018-08-15 16:36 UTC, chidioguejiofor reviewed
Okay

2018-08-15 17:42 UTC, megame24 commented on server/controllers/FollowController.js
> +    // // Ensure a user cannot unfollow him/her self
You should use just a pair of `/` for inline comments. Also, I think you might mean `follow` instead of `unfollow`.

2018-08-15 17:46 UTC, megame24 commented on server/controllers/FollowController.js
> +  static followers(req, res, next) {
You should give your controller functions more intuitive names, for this case, you can name it `getFollowers`

2018-08-15 18:12 UTC, megame24 approved these changes

2018-08-17 16:35 UTC, rhenshaw56 requested changes

2018-08-17 16:35 UTC, rhenshaw56 commented on server/controllers/FollowController.js
> +          const prepend = otherUser ? 'This user does not' : 'You don\'t';
change `prepend` to something more descriptive

2018-08-17 16:35 UTC, rhenshaw56 commented on server/controllers/FollowController.js
> +          return res.status(404).json({
use template literals

2018-08-17 16:35 UTC, rhenshaw56 commented on server/controllers/FollowController.js
> +        + ' \'followers\' of undefined') {
use template literals

2018-08-18 14:16 UTC, mppdg commented on server/controllers/FollowController.js
> +          return res.status(404).json({
Eslint flags the template literal because there is no expression embedded within the string. This can also result in hounds comment.

2018-08-18 14:19 UTC, mppdg commented on server/controllers/FollowController.js
> +        + ' \'followers\' of undefined') {
HoudCi has issue with template literals at that instance because it doesn't contain any expression

2018-08-20 15:22 UTC, rhenshaw56 requested changes

2018-08-20 15:22 UTC, rhenshaw56 commented on server/test/routes/follow.test.js
> +})
EOL exception

2018-08-20 15:27 UTC, mppdg commented on server/test/routes/follow.test.js
> +})
I have fixed the exception

2018-08-20 16:26 UTC, merged